### ISSUE TITLE
Module not connecting to Jeedom

### ISSUE THREAD

**Issue by webalexeu** [mch1307/jeedom-nhc#1] opened 2017-05-08 22:56 UTC
Hello,

I follow your guide on the wiki but unable to make the module working

Here is the log file
{ [Error: connect ETIMEDOUT 10.0.75.1:80]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '10.0.75.1',
  port: 80 }

Thank you for your help,
Alexandre

**Comment by mch1307** [comment] 2017-05-09 10:29
Hi, 
If the mentioned ip is your niko home control, then the port should be 8000 instead of 80

**Comment by webalexeu** [comment] 2017-05-09 17:51
Hello,

No, it's the IP of the Jeedom host
The log is coming from 'jeedomnhc.err.log'

Thank you for your support,
Alexandre

**Comment by mch1307** [comment] 2017-05-09 18:44
Hello,
I assume you checked the IP/port is accessible from where nodejs is running.
Can you put the log level to DEBUG, retry and send the full log? It's been a long time since I wrote this :(

**Comment by webalexeu** [comment] 2017-05-09 18:58
nodejs is running on the same host than jeedom.

I already put the log level to DEBUG but it doesn't generate more log than the one I sent to you


Something else I can check?


Thank you for your support


________________________________
De : mch1307 <notifications@github.com>
Envoyé : mardi 9 mai 2017 20:44
À : mch1307/jeedom-nhc
Cc : webalexeu; Author
Objet : Re: [mch1307/jeedom-nhc] Module not connecting to Jeedom (#1)


Hello,
I assume you checked the IP/port is accessible from where nodejs is running.
Can you put the log level to DEBUG, retry and send the full log? It's been a long time since I wrote this :(

**Comment by mch1307** [comment] 2017-05-09 19:07
can you try to put the hostname you are using when using the jeedom frontend, instead of ip address?
The full log would help, at least to see where the problem is happening

**Comment by webalexeu** [comment] 2017-05-09 19:43
When I put hostname, I don't have error anymore for now.
But it's not clear how jeedom should be configured, in the wiki, there is explanation for the location and equipment but command to send is not clear for me

Thanks,
Alexandre

**Comment by mch1307** [comment] 2017-05-09 20:13
I will close this issue as the connection problem is fixed.
You can create a new issue if you need further information

**Closed as completed by mch1307** 2017-05-09 20:13 UTC
